logging.file.name=/app/logs/production.log
logging.level.root=WARN
logging.level.br.com.fiap.esgapi=INFO
management.endpoint.health.show-details=never
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1