CREATE OR REPLACE TRIGGER TRG_EXIBE_ALERTA_USUARIOS
AFTER INSERT ON T_ALERTAS
FOR EACH ROW
BEGIN
    INSERT INTO T_EXIBE_ALERTA (ds_email, id_alerta)
    SELECT ds_email, :NEW.id_alerta
    FROM T_USUARIO;
END;
/
